all:
  hosts:
    lampstack:
      ansible_host: 158.160.25.14
      ansible_user: tony
      ansible_port: 22
  vars:
    mysql_root_password: "P@ssw0rd"
    app_user: "tony"
    http_host: "lamp.example.com"
    http_conf: "lamp.example.com.conf"
    http_port: "80"
    disable_default: true
