---
- name: Install Python
  hosts: lampstack
  become: true
  become_method: sudo
  remote_user: tony
  tasks:
  - name: Install Python
    apt:
      name: python3
      state: present

- name: configure lamp
  hosts: lampstack
  become: yes
  remote_user: tony
  become_method: sudo
  vars_files:
    - vars/default.yml
  roles:
    - apache
    - mariadb
