- hosts: all
  sudo: yes
  remote_user: tony
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python3

  tasks:
    - name: 'ensure user {{ project_name }} exists'
      user: name={{ project_name }} state=present